#!/bin/sh
cd $(dirname $0)

IEXEC_ARGS="RLC GLM OCEAN OMG SC ZRX ANT BNT LRC ROSE TRB UOS REQ"
IEXEC_IN=$(pwd)/datasets/original
IEXEC_OUT=/tmp/iexec_out
IEXEC_DATASET_FILENAME="bigquery.json"

rm -rf $IEXEC_OUT
mkdir -p $IEXEC_OUT

docker run --rm -e IEXEC_DATASET_FILENAME=$IEXEC_DATASET_FILENAME -e IEXEC_OUT=/iexec_out -e IEXEC_IN=/iexec_in -v $IEXEC_OUT:/iexec_out -v $IEXEC_IN:/iexec_in iexec-cloud-python-crypto-analysis $IEXEC_ARGS

echo
find $IEXEC_OUT
